#!/usr/bin/python3

DOMAIN = "maunainstall"
PATH = "/usr/share/mauna/locale"
KEYWORDS = "program,software,store,repository,package,add,install,uninstall,remove,apps,applications,games,flatpak"

import os
import gettext
import maunacommon.additionalfiles as additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=maunainstall
Icon=maunainstall
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
NotShowIn=KDE;
StartupNotify=true
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/maunainstall.desktop", prefix, _("Software Manager"), _("Install new applications"), suffix, keywords=KEYWORDS)

suffix = """Exec=maunainstall
Icon=maunainstall
Terminal=false
Type=Application
Encoding=UTF-8
Categories=System;
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/maunainstall-kde.desktop", prefix, _("Software Manager"), _("Install new applications"), suffix, genericName=_("Install new applications"), keywords=KEYWORDS)
