#!/bin/bash

intltool-extract --type=gettext/glade resources/maunainstall.glade
xgettext --language=Python -cTRANSLATORS --keyword=_ --keyword=N_ --output=maunainstall.pot  \
    usr/lib/mauna/maunainstall/*.py                              \
    generate_desktop_files                                                    \
    resources/maunainstall.glade.h

rm -f resources/maunainstall.glade.h
