#!/bin/bash

intltool-extract --type=gettext/glade usr/share/mauna/maunainstall/maunainstall.glade
xgettext --language=Python -cTRANSLATORS --keyword=_ --keyword=N_ --output=maunainstall.pot  \
    usr/lib/mauna/maunainstall/*.py                              \
    generate_desktop_files                                                    \
    usr/share/mauna/maunainstall/maunainstall.glade.h

rm -f usr/share/mauna/maunainstall/maunainstall.glade.h
